/*
 * generated by Xtext 2.24.0
 */
package org.xtext.idmGH.mlregDsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.idmGH.mlregDsl.parser.antlr.internal.InternalMLRegParser;
import org.xtext.idmGH.mlregDsl.services.MLRegGrammarAccess;

public class MLRegParser extends AbstractAntlrParser {

	@Inject
	private MLRegGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMLRegParser createParser(XtextTokenStream stream) {
		return new InternalMLRegParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public MLRegGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MLRegGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
