/*
 * generated by Xtext 2.24.0
 */
package org.xtext.idmGH.mlregDsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MLRegUiModule extends AbstractMLRegUiModule {

	public MLRegUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
