/*
 * generated by Xtext 2.23.0
 */
package org.xtext.idmGH.mlregDsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.xtext.idmGH.mlregDsl.mLReg.Model
import org.junit.jupiter.api.BeforeAll
import java.nio.file.Files
import java.nio.file.Paths
import java.io.File
import com.google.common.base.Charsets

@ExtendWith(InjectionExtension)
@InjectWith(MLRegInjectorProvider)
class TestPythonCompiler {
	@Inject
	ParseHelper<Model> parseHelper

	@Test
	def void testLinear10rmse() {
		val result = parseHelper.parse('''
		regression{
			file: "datasets/ozone.csv",
			testSize : 3,
			predictiveVariables : {1},
			 targetVariable: 0,
			 algorithm: Linear,
			 errorType: rmse
		}		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')

		val PythonCompiler cmpPython = new PythonCompiler(result)
		cmpPython.compileAndRun
	}
	
	@Test
	def void testLinear10r2() {
		val result = parseHelper.parse('''
		regression{
			file: "datasets/ozone.csv",
			testSize : 3,
			predictiveVariables : {1},
			 targetVariable: 0,
			 algorithm: Linear,
			 errorType: r2_score
		}		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')

		val PythonCompiler cmpPython = new PythonCompiler(result)
		cmpPython.compileAndRun
	}
	
	@Test
	def void testLinear10evs() {
		val result = parseHelper.parse('''
		regression{
			file: "datasets/ozone.csv",
			testSize : 3,
			predictiveVariables : {1},
			 targetVariable: 0,
			 algorithm: Linear,
			 errorType: r2_score
		}		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')

		val PythonCompiler cmpPython = new PythonCompiler(result)
		cmpPython.compileAndRun
	}
	
	@Test
	def void testSVM10rmse() {
		val result = parseHelper.parse('''
		regression{
			file: "datasets/ozone.csv",
			testSize : 3,
			predictiveVariables : {1},
			 targetVariable: 0,
			 algorithm: SVM,
			 errorType: rmse
		}		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')

		val PythonCompiler cmpPython = new PythonCompiler(result)
		cmpPython.compileAndRun
	}
	
	@Test
	def void testSVM10r2() {
		val result = parseHelper.parse('''
		regression{
			file: "datasets/ozone.csv",
			testSize : 3,
			predictiveVariables : {1},
			 targetVariable: 0,
			 algorithm: SVM,
			 errorType: r2_score
		}		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')

		val PythonCompiler cmpPython = new PythonCompiler(result)
		cmpPython.compileAndRun
	}
	
	@Test
	def void testSVM10mae() {
		val result = parseHelper.parse('''
		regression{
			file: "datasets/ozone.csv",
			testSize : 3,
			predictiveVariables : {1},
			 targetVariable: 0,
			 algorithm: RegressionTree,
			 errorType: mae
		}		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')

		val PythonCompiler cmpPython = new PythonCompiler(result)
		cmpPython.compileAndRun
	}

	@Test
	def void testLinearMult0rmse() {
		val result = parseHelper.parse('''
		regression{
			file: "datasets/ozone.csv",
			testSize : 3,
			predictiveVariables : {1,2,9,10},
			 targetVariable: 0,
			 algorithm: Linear,
			 errorType: rmse
		}		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')

		val PythonCompiler cmpPython = new PythonCompiler(result)
		cmpPython.compileAndRun
	}

	@Test
	def void testLinearMult0r2() {
		val result = parseHelper.parse('''
		regression{
			file: "datasets/ozone.csv",
			testSize : 3,
			predictiveVariables : {1,2,9,10},
			 targetVariable: 0,
			 algorithm: Linear,
			 errorType: r2_score
		}		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')

		val PythonCompiler cmpPython = new PythonCompiler(result)
		cmpPython.compileAndRun
	}
	
	@Test
	def void testLinearMult0mae() {
		val result = parseHelper.parse('''
		regression{
			file: "datasets/ozone.csv",
			testSize : 3,
			predictiveVariables : {1,2,9,10},
			 targetVariable: 0,
			 algorithm: Linear,
			 errorType: mae
		}		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')

		val PythonCompiler cmpPython = new PythonCompiler(result)
		cmpPython.compileAndRun
	}
	
	@Test
	def void testSVMMult0rmse() {
		val result = parseHelper.parse('''
		regression{
			file: "datasets/ozone.csv",
			testSize : 3,
			predictiveVariables : {1,2,9,10},
			 targetVariable: 0,
			 algorithm: SVM,
			 errorType: rmse
		}		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')

		val PythonCompiler cmpPython = new PythonCompiler(result)
		cmpPython.compileAndRun
	}

	@Test
	def void testSVMMult0r2() {
		val result = parseHelper.parse('''
		regression{
			file: "datasets/ozone.csv",
			testSize : 3,
			predictiveVariables : {1,2,9,10},
			 targetVariable: 0,
			 algorithm: SVM,
			 errorType: r2_score
		}		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')

		val PythonCompiler cmpPython = new PythonCompiler(result)
		cmpPython.compileAndRun
	}
	
	@Test
	def void testSVMMult0mae() {
		val result = parseHelper.parse('''
		regression{
			file: "datasets/ozone.csv",
			testSize : 3,
			predictiveVariables : {1,2,9,10},
			 targetVariable: 0,
			 algorithm: Linear,
			 errorType: mae
		}		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')

		val PythonCompiler cmpPython = new PythonCompiler(result)
		cmpPython.compileAndRun
	}


@Test
	def void testTreeMult0rmse() {
		val result = parseHelper.parse('''
		regression{
			file: "datasets/ozone.csv",
			testSize : 3,
			predictiveVariables : {1,2,9,10},
			 targetVariable: 0,
			 algorithm: RegressionTree,
			 errorType: rmse
		}		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')

		val PythonCompiler cmpPython = new PythonCompiler(result)
		cmpPython.compileAndRun
	}

	@Test
	def void testTreeMult0r2() {
		val result = parseHelper.parse('''
		regression{
			file: "datasets/ozone.csv",
			testSize : 3,
			predictiveVariables : {1,2,9,10},
			 targetVariable: 0,
			 algorithm: RegressionTree,
			 errorType: r2_score
		}		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')

		val PythonCompiler cmpPython = new PythonCompiler(result)
		cmpPython.compileAndRun
	}
	
	@Test
	def void testTreeMult0mae() {
		val result = parseHelper.parse('''
		regression{
			file: "datasets/ozone.csv",
			testSize : 3,
			predictiveVariables : {1,2,9,10},
			 targetVariable: 0,
			 algorithm: RegressionTree,
			 errorType: mae
		}		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')

		val PythonCompiler cmpPython = new PythonCompiler(result)
		cmpPython.compileAndRun
	}
	
	
}