/*
 * generated by Xtext 2.24.0
 */
package org.xtext.idmGH.mlregDsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.idmGH.mlregDsl.ui.internal.MlregDslActivator;

public class MLRegUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MlregDslActivator.getInstance().getInjector("org.xtext.idmGH.mlregDsl.MLReg");
	}

}
