/*
 * generated by Xtext 2.24.0
 */
package org.xtext.idmGH.mlregDsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MLRegStandaloneSetup extends MLRegStandaloneSetupGenerated {

	public static void doSetup() {
		new MLRegStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
