/**
 * generated by Xtext 2.24.0
 */
package org.xtext.idmGH.mlregDsl.mLReg.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.idmGH.mlregDsl.mLReg.CsvFile;
import org.xtext.idmGH.mlregDsl.mLReg.MLRegPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Csv File</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.idmGH.mlregDsl.mLReg.impl.CsvFileImpl#getCsvFile <em>Csv File</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CsvFileImpl extends MinimalEObjectImpl.Container implements CsvFile
{
  /**
   * The default value of the '{@link #getCsvFile() <em>Csv File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCsvFile()
   * @generated
   * @ordered
   */
  protected static final String CSV_FILE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCsvFile() <em>Csv File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCsvFile()
   * @generated
   * @ordered
   */
  protected String csvFile = CSV_FILE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CsvFileImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MLRegPackage.Literals.CSV_FILE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCsvFile()
  {
    return csvFile;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCsvFile(String newCsvFile)
  {
    String oldCsvFile = csvFile;
    csvFile = newCsvFile;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MLRegPackage.CSV_FILE__CSV_FILE, oldCsvFile, csvFile));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MLRegPackage.CSV_FILE__CSV_FILE:
        return getCsvFile();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MLRegPackage.CSV_FILE__CSV_FILE:
        setCsvFile((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MLRegPackage.CSV_FILE__CSV_FILE:
        setCsvFile(CSV_FILE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MLRegPackage.CSV_FILE__CSV_FILE:
        return CSV_FILE_EDEFAULT == null ? csvFile != null : !CSV_FILE_EDEFAULT.equals(csvFile);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (csvFile: ");
    result.append(csvFile);
    result.append(')');
    return result.toString();
  }

} //CsvFileImpl
