/**
 * generated by Xtext 2.24.0
 */
package org.xtext.idmGH.mlregDsl.mLReg.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.idmGH.mlregDsl.mLReg.ColVar;
import org.xtext.idmGH.mlregDsl.mLReg.MLRegPackage;
import org.xtext.idmGH.mlregDsl.mLReg.TargetVar;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Target Var</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.idmGH.mlregDsl.mLReg.impl.TargetVarImpl#getTargetVar <em>Target Var</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TargetVarImpl extends MinimalEObjectImpl.Container implements TargetVar
{
  /**
   * The cached value of the '{@link #getTargetVar() <em>Target Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTargetVar()
   * @generated
   * @ordered
   */
  protected ColVar targetVar;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TargetVarImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MLRegPackage.Literals.TARGET_VAR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ColVar getTargetVar()
  {
    return targetVar;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTargetVar(ColVar newTargetVar, NotificationChain msgs)
  {
    ColVar oldTargetVar = targetVar;
    targetVar = newTargetVar;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MLRegPackage.TARGET_VAR__TARGET_VAR, oldTargetVar, newTargetVar);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTargetVar(ColVar newTargetVar)
  {
    if (newTargetVar != targetVar)
    {
      NotificationChain msgs = null;
      if (targetVar != null)
        msgs = ((InternalEObject)targetVar).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MLRegPackage.TARGET_VAR__TARGET_VAR, null, msgs);
      if (newTargetVar != null)
        msgs = ((InternalEObject)newTargetVar).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MLRegPackage.TARGET_VAR__TARGET_VAR, null, msgs);
      msgs = basicSetTargetVar(newTargetVar, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MLRegPackage.TARGET_VAR__TARGET_VAR, newTargetVar, newTargetVar));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MLRegPackage.TARGET_VAR__TARGET_VAR:
        return basicSetTargetVar(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MLRegPackage.TARGET_VAR__TARGET_VAR:
        return getTargetVar();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MLRegPackage.TARGET_VAR__TARGET_VAR:
        setTargetVar((ColVar)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MLRegPackage.TARGET_VAR__TARGET_VAR:
        setTargetVar((ColVar)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MLRegPackage.TARGET_VAR__TARGET_VAR:
        return targetVar != null;
    }
    return super.eIsSet(featureID);
  }

} //TargetVarImpl
