/*
 * generated by Xtext 2.24.0
 */
package org.xtext.idmGH.mlregDsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMLRegScopeProvider extends DelegatingScopeProvider {
}
