/**
 * generated by Xtext 2.24.0
 */
package org.xtext.idmGH.mlregDsl.mLReg;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Col Var</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.idmGH.mlregDsl.mLReg.ColVar#getIdCol <em>Id Col</em>}</li>
 * </ul>
 *
 * @see org.xtext.idmGH.mlregDsl.mLReg.MLRegPackage#getColVar()
 * @model
 * @generated
 */
public interface ColVar extends EObject
{
  /**
   * Returns the value of the '<em><b>Id Col</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id Col</em>' attribute.
   * @see #setIdCol(int)
   * @see org.xtext.idmGH.mlregDsl.mLReg.MLRegPackage#getColVar_IdCol()
   * @model
   * @generated
   */
  int getIdCol();

  /**
   * Sets the value of the '{@link org.xtext.idmGH.mlregDsl.mLReg.ColVar#getIdCol <em>Id Col</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id Col</em>' attribute.
   * @see #getIdCol()
   * @generated
   */
  void setIdCol(int value);

} // ColVar
