/**
 * generated by Xtext 2.24.0
 */
package org.xtext.idmGH.mlregDsl.mLReg;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Csv File</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.idmGH.mlregDsl.mLReg.CsvFile#getCsvFile <em>Csv File</em>}</li>
 * </ul>
 *
 * @see org.xtext.idmGH.mlregDsl.mLReg.MLRegPackage#getCsvFile()
 * @model
 * @generated
 */
public interface CsvFile extends EObject
{
  /**
   * Returns the value of the '<em><b>Csv File</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Csv File</em>' attribute.
   * @see #setCsvFile(String)
   * @see org.xtext.idmGH.mlregDsl.mLReg.MLRegPackage#getCsvFile_CsvFile()
   * @model
   * @generated
   */
  String getCsvFile();

  /**
   * Sets the value of the '{@link org.xtext.idmGH.mlregDsl.mLReg.CsvFile#getCsvFile <em>Csv File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Csv File</em>' attribute.
   * @see #getCsvFile()
   * @generated
   */
  void setCsvFile(String value);

} // CsvFile
