/**
 * generated by Xtext 2.24.0
 */
package org.xtext.idmGH.mlregDsl.mLReg;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Error Calculation</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.idmGH.mlregDsl.mLReg.MLRegPackage#getErrorCalculation()
 * @model
 * @generated
 */
public enum ErrorCalculation implements Enumerator
{
  /**
   * The '<em><b>Mean squared error</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MEAN_SQUARED_ERROR_VALUE
   * @generated
   * @ordered
   */
  MEAN_SQUARED_ERROR(0, "mean_squared_error", "mean_squared_error"),

  /**
   * The '<em><b>Explained variance score</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EXPLAINED_VARIANCE_SCORE_VALUE
   * @generated
   * @ordered
   */
  EXPLAINED_VARIANCE_SCORE(1, "explained_variance_score", "explained_variance_score"),

  /**
   * The '<em><b>R2 score</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #R2_SCORE_VALUE
   * @generated
   * @ordered
   */
  R2_SCORE(2, "r2_score", "r2_score");

  /**
   * The '<em><b>Mean squared error</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MEAN_SQUARED_ERROR
   * @model name="mean_squared_error"
   * @generated
   * @ordered
   */
  public static final int MEAN_SQUARED_ERROR_VALUE = 0;

  /**
   * The '<em><b>Explained variance score</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EXPLAINED_VARIANCE_SCORE
   * @model name="explained_variance_score"
   * @generated
   * @ordered
   */
  public static final int EXPLAINED_VARIANCE_SCORE_VALUE = 1;

  /**
   * The '<em><b>R2 score</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #R2_SCORE
   * @model name="r2_score"
   * @generated
   * @ordered
   */
  public static final int R2_SCORE_VALUE = 2;

  /**
   * An array of all the '<em><b>Error Calculation</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final ErrorCalculation[] VALUES_ARRAY =
    new ErrorCalculation[]
    {
      MEAN_SQUARED_ERROR,
      EXPLAINED_VARIANCE_SCORE,
      R2_SCORE,
    };

  /**
   * A public read-only list of all the '<em><b>Error Calculation</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<ErrorCalculation> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Error Calculation</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ErrorCalculation get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ErrorCalculation result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Error Calculation</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ErrorCalculation getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ErrorCalculation result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Error Calculation</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ErrorCalculation get(int value)
  {
    switch (value)
    {
      case MEAN_SQUARED_ERROR_VALUE: return MEAN_SQUARED_ERROR;
      case EXPLAINED_VARIANCE_SCORE_VALUE: return EXPLAINED_VARIANCE_SCORE;
      case R2_SCORE_VALUE: return R2_SCORE;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private ErrorCalculation(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //ErrorCalculation
