/**
 * generated by Xtext 2.24.0
 */
package org.xtext.idmGH.mlregDsl.mLReg;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.idmGH.mlregDsl.mLReg.MLRegFactory
 * @model kind="package"
 * @generated
 */
public interface MLRegPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mLReg";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/idmGH/mlregDsl/MLReg";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mLReg";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MLRegPackage eINSTANCE = org.xtext.idmGH.mlregDsl.mLReg.impl.MLRegPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.idmGH.mlregDsl.mLReg.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.idmGH.mlregDsl.mLReg.impl.ModelImpl
   * @see org.xtext.idmGH.mlregDsl.mLReg.impl.MLRegPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Ml Regression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ML_REGRESSION = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.idmGH.mlregDsl.mLReg.impl.MlRegressionImpl <em>Ml Regression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.idmGH.mlregDsl.mLReg.impl.MlRegressionImpl
   * @see org.xtext.idmGH.mlregDsl.mLReg.impl.MLRegPackageImpl#getMlRegression()
   * @generated
   */
  int ML_REGRESSION = 1;

  /**
   * The feature id for the '<em><b>Csv File</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ML_REGRESSION__CSV_FILE = 0;

  /**
   * The feature id for the '<em><b>Test Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ML_REGRESSION__TEST_SIZE = 1;

  /**
   * The feature id for the '<em><b>Predictive Vars</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ML_REGRESSION__PREDICTIVE_VARS = 2;

  /**
   * The feature id for the '<em><b>Target Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ML_REGRESSION__TARGET_VAR = 3;

  /**
   * The feature id for the '<em><b>Algorithm</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ML_REGRESSION__ALGORITHM = 4;

  /**
   * The feature id for the '<em><b>Error Measure</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ML_REGRESSION__ERROR_MEASURE = 5;

  /**
   * The number of structural features of the '<em>Ml Regression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ML_REGRESSION_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.idmGH.mlregDsl.mLReg.impl.CsvFileImpl <em>Csv File</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.idmGH.mlregDsl.mLReg.impl.CsvFileImpl
   * @see org.xtext.idmGH.mlregDsl.mLReg.impl.MLRegPackageImpl#getCsvFile()
   * @generated
   */
  int CSV_FILE = 2;

  /**
   * The feature id for the '<em><b>Csv File</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSV_FILE__CSV_FILE = 0;

  /**
   * The number of structural features of the '<em>Csv File</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSV_FILE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.idmGH.mlregDsl.mLReg.impl.TestSizeImpl <em>Test Size</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.idmGH.mlregDsl.mLReg.impl.TestSizeImpl
   * @see org.xtext.idmGH.mlregDsl.mLReg.impl.MLRegPackageImpl#getTestSize()
   * @generated
   */
  int TEST_SIZE = 3;

  /**
   * The feature id for the '<em><b>Test Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_SIZE__TEST_SIZE = 0;

  /**
   * The number of structural features of the '<em>Test Size</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_SIZE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.idmGH.mlregDsl.mLReg.impl.PredictiveVarsImpl <em>Predictive Vars</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.idmGH.mlregDsl.mLReg.impl.PredictiveVarsImpl
   * @see org.xtext.idmGH.mlregDsl.mLReg.impl.MLRegPackageImpl#getPredictiveVars()
   * @generated
   */
  int PREDICTIVE_VARS = 4;

  /**
   * The feature id for the '<em><b>Predictive Var</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICTIVE_VARS__PREDICTIVE_VAR = 0;

  /**
   * The number of structural features of the '<em>Predictive Vars</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICTIVE_VARS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.idmGH.mlregDsl.mLReg.impl.TargetVarImpl <em>Target Var</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.idmGH.mlregDsl.mLReg.impl.TargetVarImpl
   * @see org.xtext.idmGH.mlregDsl.mLReg.impl.MLRegPackageImpl#getTargetVar()
   * @generated
   */
  int TARGET_VAR = 5;

  /**
   * The feature id for the '<em><b>Target Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET_VAR__TARGET_VAR = 0;

  /**
   * The number of structural features of the '<em>Target Var</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET_VAR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.idmGH.mlregDsl.mLReg.impl.AlgorithmImpl <em>Algorithm</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.idmGH.mlregDsl.mLReg.impl.AlgorithmImpl
   * @see org.xtext.idmGH.mlregDsl.mLReg.impl.MLRegPackageImpl#getAlgorithm()
   * @generated
   */
  int ALGORITHM = 6;

  /**
   * The feature id for the '<em><b>Algo Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHM__ALGO_NAME = 0;

  /**
   * The number of structural features of the '<em>Algorithm</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.idmGH.mlregDsl.mLReg.impl.ErrorMeasureImpl <em>Error Measure</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.idmGH.mlregDsl.mLReg.impl.ErrorMeasureImpl
   * @see org.xtext.idmGH.mlregDsl.mLReg.impl.MLRegPackageImpl#getErrorMeasure()
   * @generated
   */
  int ERROR_MEASURE = 7;

  /**
   * The feature id for the '<em><b>Error Measure</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ERROR_MEASURE__ERROR_MEASURE = 0;

  /**
   * The number of structural features of the '<em>Error Measure</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ERROR_MEASURE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.idmGH.mlregDsl.mLReg.impl.ColVarImpl <em>Col Var</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.idmGH.mlregDsl.mLReg.impl.ColVarImpl
   * @see org.xtext.idmGH.mlregDsl.mLReg.impl.MLRegPackageImpl#getColVar()
   * @generated
   */
  int COL_VAR = 8;

  /**
   * The feature id for the '<em><b>Id Col</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COL_VAR__ID_COL = 0;

  /**
   * The number of structural features of the '<em>Col Var</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COL_VAR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.idmGH.mlregDsl.mLReg.AlgoName <em>Algo Name</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.idmGH.mlregDsl.mLReg.AlgoName
   * @see org.xtext.idmGH.mlregDsl.mLReg.impl.MLRegPackageImpl#getAlgoName()
   * @generated
   */
  int ALGO_NAME = 9;

  /**
   * The meta object id for the '{@link org.xtext.idmGH.mlregDsl.mLReg.ErrorCalculation <em>Error Calculation</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.idmGH.mlregDsl.mLReg.ErrorCalculation
   * @see org.xtext.idmGH.mlregDsl.mLReg.impl.MLRegPackageImpl#getErrorCalculation()
   * @generated
   */
  int ERROR_CALCULATION = 10;


  /**
   * Returns the meta object for class '{@link org.xtext.idmGH.mlregDsl.mLReg.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.idmGH.mlregDsl.mLReg.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.idmGH.mlregDsl.mLReg.Model#getMlRegression <em>Ml Regression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ml Regression</em>'.
   * @see org.xtext.idmGH.mlregDsl.mLReg.Model#getMlRegression()
   * @see #getModel()
   * @generated
   */
  EReference getModel_MlRegression();

  /**
   * Returns the meta object for class '{@link org.xtext.idmGH.mlregDsl.mLReg.MlRegression <em>Ml Regression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ml Regression</em>'.
   * @see org.xtext.idmGH.mlregDsl.mLReg.MlRegression
   * @generated
   */
  EClass getMlRegression();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.idmGH.mlregDsl.mLReg.MlRegression#getCsvFile <em>Csv File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Csv File</em>'.
   * @see org.xtext.idmGH.mlregDsl.mLReg.MlRegression#getCsvFile()
   * @see #getMlRegression()
   * @generated
   */
  EReference getMlRegression_CsvFile();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.idmGH.mlregDsl.mLReg.MlRegression#getTestSize <em>Test Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Test Size</em>'.
   * @see org.xtext.idmGH.mlregDsl.mLReg.MlRegression#getTestSize()
   * @see #getMlRegression()
   * @generated
   */
  EReference getMlRegression_TestSize();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.idmGH.mlregDsl.mLReg.MlRegression#getPredictiveVars <em>Predictive Vars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Predictive Vars</em>'.
   * @see org.xtext.idmGH.mlregDsl.mLReg.MlRegression#getPredictiveVars()
   * @see #getMlRegression()
   * @generated
   */
  EReference getMlRegression_PredictiveVars();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.idmGH.mlregDsl.mLReg.MlRegression#getTargetVar <em>Target Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Target Var</em>'.
   * @see org.xtext.idmGH.mlregDsl.mLReg.MlRegression#getTargetVar()
   * @see #getMlRegression()
   * @generated
   */
  EReference getMlRegression_TargetVar();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.idmGH.mlregDsl.mLReg.MlRegression#getAlgorithm <em>Algorithm</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Algorithm</em>'.
   * @see org.xtext.idmGH.mlregDsl.mLReg.MlRegression#getAlgorithm()
   * @see #getMlRegression()
   * @generated
   */
  EReference getMlRegression_Algorithm();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.idmGH.mlregDsl.mLReg.MlRegression#getErrorMeasure <em>Error Measure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Error Measure</em>'.
   * @see org.xtext.idmGH.mlregDsl.mLReg.MlRegression#getErrorMeasure()
   * @see #getMlRegression()
   * @generated
   */
  EReference getMlRegression_ErrorMeasure();

  /**
   * Returns the meta object for class '{@link org.xtext.idmGH.mlregDsl.mLReg.CsvFile <em>Csv File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Csv File</em>'.
   * @see org.xtext.idmGH.mlregDsl.mLReg.CsvFile
   * @generated
   */
  EClass getCsvFile();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.idmGH.mlregDsl.mLReg.CsvFile#getCsvFile <em>Csv File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Csv File</em>'.
   * @see org.xtext.idmGH.mlregDsl.mLReg.CsvFile#getCsvFile()
   * @see #getCsvFile()
   * @generated
   */
  EAttribute getCsvFile_CsvFile();

  /**
   * Returns the meta object for class '{@link org.xtext.idmGH.mlregDsl.mLReg.TestSize <em>Test Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test Size</em>'.
   * @see org.xtext.idmGH.mlregDsl.mLReg.TestSize
   * @generated
   */
  EClass getTestSize();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.idmGH.mlregDsl.mLReg.TestSize#getTestSize <em>Test Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Test Size</em>'.
   * @see org.xtext.idmGH.mlregDsl.mLReg.TestSize#getTestSize()
   * @see #getTestSize()
   * @generated
   */
  EAttribute getTestSize_TestSize();

  /**
   * Returns the meta object for class '{@link org.xtext.idmGH.mlregDsl.mLReg.PredictiveVars <em>Predictive Vars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predictive Vars</em>'.
   * @see org.xtext.idmGH.mlregDsl.mLReg.PredictiveVars
   * @generated
   */
  EClass getPredictiveVars();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.idmGH.mlregDsl.mLReg.PredictiveVars#getPredictiveVar <em>Predictive Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Predictive Var</em>'.
   * @see org.xtext.idmGH.mlregDsl.mLReg.PredictiveVars#getPredictiveVar()
   * @see #getPredictiveVars()
   * @generated
   */
  EReference getPredictiveVars_PredictiveVar();

  /**
   * Returns the meta object for class '{@link org.xtext.idmGH.mlregDsl.mLReg.TargetVar <em>Target Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Target Var</em>'.
   * @see org.xtext.idmGH.mlregDsl.mLReg.TargetVar
   * @generated
   */
  EClass getTargetVar();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.idmGH.mlregDsl.mLReg.TargetVar#getTargetVar <em>Target Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Target Var</em>'.
   * @see org.xtext.idmGH.mlregDsl.mLReg.TargetVar#getTargetVar()
   * @see #getTargetVar()
   * @generated
   */
  EReference getTargetVar_TargetVar();

  /**
   * Returns the meta object for class '{@link org.xtext.idmGH.mlregDsl.mLReg.Algorithm <em>Algorithm</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Algorithm</em>'.
   * @see org.xtext.idmGH.mlregDsl.mLReg.Algorithm
   * @generated
   */
  EClass getAlgorithm();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.idmGH.mlregDsl.mLReg.Algorithm#getAlgoName <em>Algo Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Algo Name</em>'.
   * @see org.xtext.idmGH.mlregDsl.mLReg.Algorithm#getAlgoName()
   * @see #getAlgorithm()
   * @generated
   */
  EAttribute getAlgorithm_AlgoName();

  /**
   * Returns the meta object for class '{@link org.xtext.idmGH.mlregDsl.mLReg.ErrorMeasure <em>Error Measure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Error Measure</em>'.
   * @see org.xtext.idmGH.mlregDsl.mLReg.ErrorMeasure
   * @generated
   */
  EClass getErrorMeasure();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.idmGH.mlregDsl.mLReg.ErrorMeasure#getErrorMeasure <em>Error Measure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Error Measure</em>'.
   * @see org.xtext.idmGH.mlregDsl.mLReg.ErrorMeasure#getErrorMeasure()
   * @see #getErrorMeasure()
   * @generated
   */
  EAttribute getErrorMeasure_ErrorMeasure();

  /**
   * Returns the meta object for class '{@link org.xtext.idmGH.mlregDsl.mLReg.ColVar <em>Col Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Col Var</em>'.
   * @see org.xtext.idmGH.mlregDsl.mLReg.ColVar
   * @generated
   */
  EClass getColVar();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.idmGH.mlregDsl.mLReg.ColVar#getIdCol <em>Id Col</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id Col</em>'.
   * @see org.xtext.idmGH.mlregDsl.mLReg.ColVar#getIdCol()
   * @see #getColVar()
   * @generated
   */
  EAttribute getColVar_IdCol();

  /**
   * Returns the meta object for enum '{@link org.xtext.idmGH.mlregDsl.mLReg.AlgoName <em>Algo Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Algo Name</em>'.
   * @see org.xtext.idmGH.mlregDsl.mLReg.AlgoName
   * @generated
   */
  EEnum getAlgoName();

  /**
   * Returns the meta object for enum '{@link org.xtext.idmGH.mlregDsl.mLReg.ErrorCalculation <em>Error Calculation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Error Calculation</em>'.
   * @see org.xtext.idmGH.mlregDsl.mLReg.ErrorCalculation
   * @generated
   */
  EEnum getErrorCalculation();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MLRegFactory getMLRegFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.idmGH.mlregDsl.mLReg.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.idmGH.mlregDsl.mLReg.impl.ModelImpl
     * @see org.xtext.idmGH.mlregDsl.mLReg.impl.MLRegPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Ml Regression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ML_REGRESSION = eINSTANCE.getModel_MlRegression();

    /**
     * The meta object literal for the '{@link org.xtext.idmGH.mlregDsl.mLReg.impl.MlRegressionImpl <em>Ml Regression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.idmGH.mlregDsl.mLReg.impl.MlRegressionImpl
     * @see org.xtext.idmGH.mlregDsl.mLReg.impl.MLRegPackageImpl#getMlRegression()
     * @generated
     */
    EClass ML_REGRESSION = eINSTANCE.getMlRegression();

    /**
     * The meta object literal for the '<em><b>Csv File</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ML_REGRESSION__CSV_FILE = eINSTANCE.getMlRegression_CsvFile();

    /**
     * The meta object literal for the '<em><b>Test Size</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ML_REGRESSION__TEST_SIZE = eINSTANCE.getMlRegression_TestSize();

    /**
     * The meta object literal for the '<em><b>Predictive Vars</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ML_REGRESSION__PREDICTIVE_VARS = eINSTANCE.getMlRegression_PredictiveVars();

    /**
     * The meta object literal for the '<em><b>Target Var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ML_REGRESSION__TARGET_VAR = eINSTANCE.getMlRegression_TargetVar();

    /**
     * The meta object literal for the '<em><b>Algorithm</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ML_REGRESSION__ALGORITHM = eINSTANCE.getMlRegression_Algorithm();

    /**
     * The meta object literal for the '<em><b>Error Measure</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ML_REGRESSION__ERROR_MEASURE = eINSTANCE.getMlRegression_ErrorMeasure();

    /**
     * The meta object literal for the '{@link org.xtext.idmGH.mlregDsl.mLReg.impl.CsvFileImpl <em>Csv File</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.idmGH.mlregDsl.mLReg.impl.CsvFileImpl
     * @see org.xtext.idmGH.mlregDsl.mLReg.impl.MLRegPackageImpl#getCsvFile()
     * @generated
     */
    EClass CSV_FILE = eINSTANCE.getCsvFile();

    /**
     * The meta object literal for the '<em><b>Csv File</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CSV_FILE__CSV_FILE = eINSTANCE.getCsvFile_CsvFile();

    /**
     * The meta object literal for the '{@link org.xtext.idmGH.mlregDsl.mLReg.impl.TestSizeImpl <em>Test Size</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.idmGH.mlregDsl.mLReg.impl.TestSizeImpl
     * @see org.xtext.idmGH.mlregDsl.mLReg.impl.MLRegPackageImpl#getTestSize()
     * @generated
     */
    EClass TEST_SIZE = eINSTANCE.getTestSize();

    /**
     * The meta object literal for the '<em><b>Test Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEST_SIZE__TEST_SIZE = eINSTANCE.getTestSize_TestSize();

    /**
     * The meta object literal for the '{@link org.xtext.idmGH.mlregDsl.mLReg.impl.PredictiveVarsImpl <em>Predictive Vars</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.idmGH.mlregDsl.mLReg.impl.PredictiveVarsImpl
     * @see org.xtext.idmGH.mlregDsl.mLReg.impl.MLRegPackageImpl#getPredictiveVars()
     * @generated
     */
    EClass PREDICTIVE_VARS = eINSTANCE.getPredictiveVars();

    /**
     * The meta object literal for the '<em><b>Predictive Var</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICTIVE_VARS__PREDICTIVE_VAR = eINSTANCE.getPredictiveVars_PredictiveVar();

    /**
     * The meta object literal for the '{@link org.xtext.idmGH.mlregDsl.mLReg.impl.TargetVarImpl <em>Target Var</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.idmGH.mlregDsl.mLReg.impl.TargetVarImpl
     * @see org.xtext.idmGH.mlregDsl.mLReg.impl.MLRegPackageImpl#getTargetVar()
     * @generated
     */
    EClass TARGET_VAR = eINSTANCE.getTargetVar();

    /**
     * The meta object literal for the '<em><b>Target Var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TARGET_VAR__TARGET_VAR = eINSTANCE.getTargetVar_TargetVar();

    /**
     * The meta object literal for the '{@link org.xtext.idmGH.mlregDsl.mLReg.impl.AlgorithmImpl <em>Algorithm</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.idmGH.mlregDsl.mLReg.impl.AlgorithmImpl
     * @see org.xtext.idmGH.mlregDsl.mLReg.impl.MLRegPackageImpl#getAlgorithm()
     * @generated
     */
    EClass ALGORITHM = eINSTANCE.getAlgorithm();

    /**
     * The meta object literal for the '<em><b>Algo Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALGORITHM__ALGO_NAME = eINSTANCE.getAlgorithm_AlgoName();

    /**
     * The meta object literal for the '{@link org.xtext.idmGH.mlregDsl.mLReg.impl.ErrorMeasureImpl <em>Error Measure</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.idmGH.mlregDsl.mLReg.impl.ErrorMeasureImpl
     * @see org.xtext.idmGH.mlregDsl.mLReg.impl.MLRegPackageImpl#getErrorMeasure()
     * @generated
     */
    EClass ERROR_MEASURE = eINSTANCE.getErrorMeasure();

    /**
     * The meta object literal for the '<em><b>Error Measure</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ERROR_MEASURE__ERROR_MEASURE = eINSTANCE.getErrorMeasure_ErrorMeasure();

    /**
     * The meta object literal for the '{@link org.xtext.idmGH.mlregDsl.mLReg.impl.ColVarImpl <em>Col Var</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.idmGH.mlregDsl.mLReg.impl.ColVarImpl
     * @see org.xtext.idmGH.mlregDsl.mLReg.impl.MLRegPackageImpl#getColVar()
     * @generated
     */
    EClass COL_VAR = eINSTANCE.getColVar();

    /**
     * The meta object literal for the '<em><b>Id Col</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COL_VAR__ID_COL = eINSTANCE.getColVar_IdCol();

    /**
     * The meta object literal for the '{@link org.xtext.idmGH.mlregDsl.mLReg.AlgoName <em>Algo Name</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.idmGH.mlregDsl.mLReg.AlgoName
     * @see org.xtext.idmGH.mlregDsl.mLReg.impl.MLRegPackageImpl#getAlgoName()
     * @generated
     */
    EEnum ALGO_NAME = eINSTANCE.getAlgoName();

    /**
     * The meta object literal for the '{@link org.xtext.idmGH.mlregDsl.mLReg.ErrorCalculation <em>Error Calculation</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.idmGH.mlregDsl.mLReg.ErrorCalculation
     * @see org.xtext.idmGH.mlregDsl.mLReg.impl.MLRegPackageImpl#getErrorCalculation()
     * @generated
     */
    EEnum ERROR_CALCULATION = eINSTANCE.getErrorCalculation();

  }

} //MLRegPackage
