/**
 * generated by Xtext 2.24.0
 */
package org.xtext.idmGH.mlregDsl.mLReg;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.idmGH.mlregDsl.mLReg.MLRegPackage
 * @generated
 */
public interface MLRegFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MLRegFactory eINSTANCE = org.xtext.idmGH.mlregDsl.mLReg.impl.MLRegFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Ml Regression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ml Regression</em>'.
   * @generated
   */
  MlRegression createMlRegression();

  /**
   * Returns a new object of class '<em>Csv File</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Csv File</em>'.
   * @generated
   */
  CsvFile createCsvFile();

  /**
   * Returns a new object of class '<em>Test Size</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Test Size</em>'.
   * @generated
   */
  TestSize createTestSize();

  /**
   * Returns a new object of class '<em>Predictive Vars</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Predictive Vars</em>'.
   * @generated
   */
  PredictiveVars createPredictiveVars();

  /**
   * Returns a new object of class '<em>Target Var</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Target Var</em>'.
   * @generated
   */
  TargetVar createTargetVar();

  /**
   * Returns a new object of class '<em>Algorithm</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Algorithm</em>'.
   * @generated
   */
  Algorithm createAlgorithm();

  /**
   * Returns a new object of class '<em>Error Measure</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Error Measure</em>'.
   * @generated
   */
  ErrorMeasure createErrorMeasure();

  /**
   * Returns a new object of class '<em>Col Var</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Col Var</em>'.
   * @generated
   */
  ColVar createColVar();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MLRegPackage getMLRegPackage();

} //MLRegFactory
