/**
 * generated by Xtext 2.24.0
 */
package org.xtext.idmGH.mlregDsl.mLReg;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.idmGH.mlregDsl.mLReg.Model#getMlRegression <em>Ml Regression</em>}</li>
 * </ul>
 *
 * @see org.xtext.idmGH.mlregDsl.mLReg.MLRegPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Ml Regression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ml Regression</em>' containment reference.
   * @see #setMlRegression(MlRegression)
   * @see org.xtext.idmGH.mlregDsl.mLReg.MLRegPackage#getModel_MlRegression()
   * @model containment="true"
   * @generated
   */
  MlRegression getMlRegression();

  /**
   * Sets the value of the '{@link org.xtext.idmGH.mlregDsl.mLReg.Model#getMlRegression <em>Ml Regression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ml Regression</em>' containment reference.
   * @see #getMlRegression()
   * @generated
   */
  void setMlRegression(MlRegression value);

} // Model
