/**
 * generated by Xtext 2.24.0
 */
package org.xtext.idmGH.mlregDsl.mLReg;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Target Var</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.idmGH.mlregDsl.mLReg.TargetVar#getTargetVar <em>Target Var</em>}</li>
 * </ul>
 *
 * @see org.xtext.idmGH.mlregDsl.mLReg.MLRegPackage#getTargetVar()
 * @model
 * @generated
 */
public interface TargetVar extends EObject
{
  /**
   * Returns the value of the '<em><b>Target Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target Var</em>' containment reference.
   * @see #setTargetVar(ColVar)
   * @see org.xtext.idmGH.mlregDsl.mLReg.MLRegPackage#getTargetVar_TargetVar()
   * @model containment="true"
   * @generated
   */
  ColVar getTargetVar();

  /**
   * Sets the value of the '{@link org.xtext.idmGH.mlregDsl.mLReg.TargetVar#getTargetVar <em>Target Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target Var</em>' containment reference.
   * @see #getTargetVar()
   * @generated
   */
  void setTargetVar(ColVar value);

} // TargetVar
