/**
 * generated by Xtext 2.24.0
 */
package org.xtext.idmGH.mlregDsl.mLReg;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Test Size</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.idmGH.mlregDsl.mLReg.TestSize#getTestSize <em>Test Size</em>}</li>
 * </ul>
 *
 * @see org.xtext.idmGH.mlregDsl.mLReg.MLRegPackage#getTestSize()
 * @model
 * @generated
 */
public interface TestSize extends EObject
{
  /**
   * Returns the value of the '<em><b>Test Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Test Size</em>' attribute.
   * @see #setTestSize(int)
   * @see org.xtext.idmGH.mlregDsl.mLReg.MLRegPackage#getTestSize_TestSize()
   * @model
   * @generated
   */
  int getTestSize();

  /**
   * Sets the value of the '{@link org.xtext.idmGH.mlregDsl.mLReg.TestSize#getTestSize <em>Test Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Test Size</em>' attribute.
   * @see #getTestSize()
   * @generated
   */
  void setTestSize(int value);

} // TestSize
